name: Deploy to WordPress.org
on:
    workflow_dispatch:
    
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Install node dependencies
    run: npm install

    - name: Compile Javascript App
    run: npm run build

    - name: Create Relase
    run: gh release create
    
    # - name: Create Block Theme Plugin Deploy to WordPress.org
    #   uses: 10up/action-wordpress-plugin-deploy@stable
    #   env:
    #     SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
    #     SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
