name: Deploy to WordPress.org

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'New release'
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Install node dependencies
    run: npm install

    - name: Compile Javascript App
    run: npm run build

    - name: Create Relase
    run: gh release create