name: Deploy to WordPress.org

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Install node dependencies
      run: npm install

    - name: Compile Javascript App
      run: npm run build

    - name: Update tag
      id: update-tag
      env:
        RELEASE_TYPE: ${{ github.event.inputs.release_type }}
      run: npm run update-tag 

    - name: Create Relase
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        git config user.name 'Matias Benedetto'
        git config user.email 'matias.benedetto@gmail.com'
        git config --global --add --bool push.autoSetupRemote true
        git diff-index --quiet HEAD -- || ( git add package.json && git commit -m "version bump" && git push )
        gh release create ${{steps.update-tag.outputs.NEW_TAG }} --generate-notes
